import { LegalSection, PublicLegalDocument } from '../src/apps/home/PublicPageShell';

export default function TermsOfService() {
  return (
    <PublicLegalDocument title='Terms of Service' updated='Last Updated: 1/24/2024'>
      <LegalSection>
        Welcome to bigAGI! By accessing or using our chatbot application, you agree to be bound by these Terms of Service. If you disagree with any part of
        the terms, you may not access the service.
      </LegalSection>

      <LegalSection title='1. Use of Our Service'>
        bigAGI provides a chatbot service. Users are responsible for the information they input into bigAGI. We do not endorse or assume any responsibility
        for the content generated by the chatbot.
      </LegalSection>

      <LegalSection title='2. Content'>
        You understand that all information, whether publicly posted or privately transmitted through bigAGI, is the sole responsibility of the person from
        whom such content originated. We do not control the content passed through the chatbot and, as such, do not guarantee the accuracy, integrity, or
        quality of such content.
      </LegalSection>

      <LegalSection title='3. Limitation of Liability'>
        bigAGI shall not be liable for any statements or conduct of any third party using the service. You agree that your use of the chatbot is at your sole
        risk and that bigAGI is not liable for any content generated, including but not limited to errors, defamatory statements, or other types of content.
      </LegalSection>

      <LegalSection title='4. Modifications to Service'>
        bigAGI reserves the right to modify or discontinue, temporarily or permanently, the service with or without notice. You agree that bigAGI shall not be
        liable to you or to any third party for any modification, suspension, or discontinuance of the service.
      </LegalSection>

      <LegalSection title='5. General Conditions'>
        We reserve the right to update and change the Terms of Service from time to time without notice. Your continued use of the service after any such
        changes shall constitute your consent to such changes.
      </LegalSection>

      <LegalSection>
        For any questions or inquiries regarding the Terms of Service, please contact us.
      </LegalSection>

      <LegalSection>
        This document was last updated on 1/24/2024.
      </LegalSection>
    </PublicLegalDocument>
  );
}
